### ISSUE TITLE
Backtrace "ReferenceError: weakly-referenced object no longer exists"

### ISSUE THREAD

**Issue by hartwork** [costela/wile#16]
Seems to happen with Python 3.4 but not with Python 2.7:
```
# wile --staging --account-key /home/letsencrypt/.wile/_STAGING-account.key --verbose cert request --separate-chain --min-valid-time 9d --output-dir /etc/letsencrypt/live/foo.example.org foo.example.org:/var/www/foo.example.org/htdocs/
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-staging.api.letsencrypt.org
INFO:wile.register:automatically accepting ToS
INFO:wile.cert:requesting challange for foo.example.org in /var/www/foo.example.org/htdocs/
INFO:wile.cert:storing validation of /var/www/foo.example.org/htdocs/
INFO:wile.cert:storing validation to /var/www/foo.example.org/htdocs/.well-known/acme-challenge/....................
Exception ignored in: <bound method ClientNetwork.__del__ of <acme.client.ClientNetwork object at 0x7f1b7041c550>>
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/acme/client.py", line 534, in __del__
    self.session.close()
  File "/usr/lib64/python3.4/site-packages/requests/sessions.py", line 676, in close
    for v in self.adapters.values():
  File "/usr/lib64/python3.4/_collections_abc.py", line 512, in __iter__
    for key in self._mapping:
  File "/usr/lib64/python3.4/collections/__init__.py", line 91, in __iter__
    curr = root.next
ReferenceError: weakly-referenced object no longer exists
```

**Comment by costela** [comment]
I can't reproduce this here. Looks a bit like some connection tear-down issue (it's happening inside of `ClientNetwork.__del__`). What versions of `acme` and `requests` are you using? I'm not sure this is actually a `wile` issue.

**Comment by hartwork** [comment]
python 3.4.5
acme 0.11.1
requests 2.11.1

**Comment by hartwork** [comment]
Have not seen this issue again since then. Close as obsolete?

**Comment by costela** [comment]
agreed! 👍🏼
