### ISSUE TITLE
With acme 0.22.0: AttributeError: 'NoneType' object has no attribute 'post'

### ISSUE THREAD

**Issue by hartwork** [costela/wile#34]
Would be cool to have this fixed so I can unbreak the SSL cert on the related website:

wile: 1.0.1
acme: 0.22.0
click: 6.7

```
# sudo -u letsencrypt [..]/python2.7/wile --account-key [..] --verbose cert request --separate-chain --min-valid-time 9d --output-dir [..] [..]:[..]
INFO:wile.reg:starting registration for email:"None", phone:"None"
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/wile", line 11, in <module>
    load_entry_point('wile==0.0.0', 'console_scripts', 'wile')()
  File "/usr/lib64/python2.7/site-packages/wile/__init__.py", line 112, in main
    return wile(obj=LazyClient())
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/wile/cert.py", line 92, in request
    regr = ctx.invoke(reg.register, quiet=True, auto_accept_tos=True)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/wile/reg.py", line 30, in register
    regr = ctx.obj.acme.register(messages.NewRegistration.from_data(email=email, phone=phone))
  File "/usr/lib64/python2.7/site-packages/acme/client.py", line 281, in register
    response = self._post(self.directory[new_reg], new_reg)
  File "/usr/lib64/python2.7/site-packages/acme/client.py", line 90, in _post
    return self.net.post(*args, **kwargs)
AttributeError: 'NoneType' object has no attribute 'post'
ERROR: cert sync failed
```

**Comment by hartwork** [comment]
It's a bug in acme 0.22.0 it seems. More details in a minute.

**Comment by hartwork** [comment]
It's a bug in acme 0.22.0, see above.

**Comment by hartwork** [comment]
For mitigation, we could change `'acme >= 0.21.0'` to `'acme >= 0.21.0, != 0.22.0'` in wile. What do you think? Should I make a pull request?

**Comment by costela** [comment]
yes, I was hoping they would release 0.22.1 this weekend, but maybe it's not a bad idea to be on the safe side. I'm uploading a new version right now.

**Comment by hartwork** [comment]
With https://github.com/costela/wile/blob/823e929b3686744817c8d110c0dd16fd36ff9d58/setup.py#L25 on `master` I think this ticket can be closed.
