### ISSUE TITLE
Crash/backtrace on `.well-known` folder creation failure

### ISSUE THREAD

**Issue by hartwork** [costela/wile#9]
It would be cool if wile would print a nice error message instead:
```
$ wile --staging --account-key ~/.wile/STAGING-account.key --verbose cert request --separate-chain --output-dir /etc/letsencrypt/archive/foo.example.org foo.example.org:/var/www/foo.example.org/htdocs/                                                                                                        
INFO:wile.register:automatically accepting ToS                                                                                                                          
INFO:wile.cert:requesting challange for foo.example.org in /var/www/foo.example.org/htdocs/                                                                         
INFO:wile.cert:storing validation of /var/www/foo.example.org/htdocs/                                                                                                 
Traceback (most recent call last):                                                                                                                                      
  File "/usr/lib/python-exec/python2.7/wile", line 11, in <module>                                                                                                      
    load_entry_point('wile==0.0.0', 'console_scripts', 'wile')()                                                                                                        
  File "/usr/lib64/python2.7/site-packages/wile.py", line 91, in main                                                                                                   
    return wile(obj={})                                                                                                                                                 
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 722, in __call__                                                                                        
    return self.main(*args, **kwargs)                                                                                                                                   
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 697, in main                                                                                            
    rv = self.invoke(ctx)                                                                                                                                               
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/cert.py", line 67, in request
    _store_webroot_validation(webroot, challb, chall_validation)
  File "/usr/lib64/python2.7/site-packages/cert.py", line 150, in _store_webroot_validation
    os.makedirs(os.path.join(webroot, challb.URI_ROOT_PATH), 0o755)
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/var/www/foo.example.org/htdocs/.well-known'
```

**Comment by hartwork** [comment]
Thank you!
